"""interview sessions, turns, media assets, proctor events

Revision ID: 157743146ded
Revises: ceb61005424a
Create Date: 2026-09-03 19:07:25.750823

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '157743146ded'
down_revision: str | None = 'ceb61005424a'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('created', 'consent_pending', 'ready', 'in_progress', 'disconnected', 'completed', 'abandoned', 'scoring', 'scored', 'failed', 'released', name='sessionstate', native_enum=False, length=20), nullable=False),
    sa.Column('interview_plan', sa.JSON(), nullable=False),
    sa.Column('plan_version', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_s', sa.Integer(), nullable=False),
    sa.Column('disconnect_count', sa.Integer(), nullable=False),
    sa.Column('grace_used_s', sa.Integer(), nullable=False),
    sa.Column('end_reason', sa.Enum('completed', 'time_cap', 'abandoned', 'error', 'candidate_ended', name='endreason', native_enum=False, length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('interview_turns',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('agent', 'candidate', name='speaker', native_enum=False, length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stt_provider', sa.String(length=50), nullable=True),
    sa.Column('stt_model', sa.String(length=50), nullable=True),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('audio_key', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_index', name='uq_turn_session_index')
    )
    op.create_table('media_assets',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('video', 'audio', 'screen', name='mediakind', native_enum=False, length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('uploading', 'ready', 'failed', name='mediastatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_session_id'), 'media_assets', ['session_id'], unique=False)
    op.create_table('proctor_events',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proctor_events_session_occurred', 'proctor_events', ['session_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proctor_events_session_occurred', table_name='proctor_events')
    op.drop_table('proctor_events')
    op.drop_index(op.f('ix_media_assets_session_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_table('interview_turns')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
