"""add retention and erasure fields

Revision ID: c0d4ed1dc701
Revises: fe383be6ced4
Create Date: 2026-09-04 20:15:05.810632

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c0d4ed1dc701'
down_revision: str | None = 'fe383be6ced4'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('data_purged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('erased_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'erased_at')
    op.drop_column('applications', 'data_purged_at')
    op.drop_column('applications', 'decided_at')
    # ### end Alembic commands ###
