"""add scores and score_dimensions

Revision ID: fe383be6ced4
Revises: 157743146ded
Create Date: 2026-09-04 19:09:40.141879

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fe383be6ced4'
down_revision: str | None = '157743146ded'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('overall', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('recommendation_band', sa.Enum('strong', 'promising', 'mixed', 'weak', name='recommendationband', native_enum=False, length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('redaction_version', sa.String(length=20), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'complete', 'failed', 'needs_review', name='scorestatus', native_enum=False, length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('score_dimensions',
    sa.Column('score_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('evidence_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value BETWEEN 1 AND 5', name='ck_score_dimension_value'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_dimensions_score_id'), 'score_dimensions', ['score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_dimensions_score_id'), table_name='score_dimensions')
    op.drop_table('score_dimensions')
    op.drop_table('scores')
    # ### end Alembic commands ###
